# Capstone Project

# (Crimes in India)

# Phase 1

# Data Collection/preparation part.

REQ. NUMBER -1

The population of each state.

In [2]:
import pandas as pd

THE DATA ASKED IS COLLECTED FROM "https://visualize.data.gov.in/?inst=afec9f11-fa3c-46e6-adbf-3cd1e53959c5". WHICH SHOWS POPULATION OF INDIA FROM THE YEAR 2001 TO 2011.

In [5]:
population_data = pd.read_csv(r"C:\Users\Sayan Mondal\Downloads\population.csv")

In [6]:
population_data

,State/Union Territory,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,Andhra Pradesh,76542,77710,78616,79502,80369,81219,82049,82858,83649,84426,85188
1,Arunachal Pradesh,1110,1121,1135,1149,1163,1178,1192,1206,1221,1235,1249
2,Assam,26873,27317,27719,28114,28506,28896,29282,29660,30037,30413,30791
3,Bihar,84385,85568,87131,88662,90162,91631,93068,94474,95849,97192,98505
4,Chhattisgarh,20969,21412,21764,22111,22455,22797,23134,23466,23796,24124,24452
5,Goa,1360,1357,1389,1429,1474,1517,1568,1629,1691,1749,1799
6,Gujarat,51349,52079,52944,53798,54642,55475,56298,57109,57910,58702,59485
7,Haryana,21467,21837,22273,22707,23140,23569,23997,24425,24849,25270,25686
8,Himachal Pradesh,6131,6203,6279,6354,6426,6498,6567,6636,6702,6767,6831
9,Jammu & Kashmir,10291,10395,10556,10717,10877,11035,11192,11350,11506,11659,11806
10,Jharkhand,27271,27737,28206,28664,29116,29567,30008,30438,30865,31293,31727
11,Karnataka,53321,53969,54654,55327,55992,56647,57292,57927,58552,59170,59780
12,Kerala,31972,32303,32591,32875,33154,33426,33694,33958,34216,34467,34708
13,Madhya Pradesh,61055,62312,63521,64720,65910,67093,68266,69428,70582,71732,72879
14,Maharashtra,97926,99371,100966,102566,104160,105740,107321,108908,110485,112042,113569
15,Manipur,2180,2212,2240,2268,2296,2325,2353,2381,2409,2438,2466
16,Meghalaya,2353,2367,2397,2427,2457,2488,2518,2548,2578,2609,2639
17,Mizoram,900,907,919,930,942,953,965,976,988,1000,1011
18,Nagaland,2052,2031,2057,2083,2109,2135,2161,2187,2212,2238,2264
19,Odisha,37079,37503,37921,38329,38728,39121,39505,39877,40243,40603,40961
20,Punjab,24625,24899,25243,25586,25925,26257,26587,26916,27240,27556,27861
21,Rajasthan,57370,58350,59512,60670,61818,62951,64077,65200,66310,67401,68468
22,Sikkim,552,552,559,566,573,580,587,595,602,609,616
23,Tamil Nadu,62742,63332,63883,64416,64933,65435,65919,66386,66836,67273,67698
24,Tripura,3206,3265,3307,3349,3390,3432,3474,3515,3557,3599,3641
25,Uttar Pradesh,168451,171532,174956,178406,181868,185330,188812,192325,195841,199347,202830
26,Uttrakhand,8578,8720,8866,9013,9160,9305,9451,9597,9742,9885,10027
27,West Bengal,80729,81928,82935,83902,84842,85768,86659,87506,88335,89158,89987
28,Andaman & Nicobar Islands,359,372,385,399,413,427,442,458,474,489,502
29,Chandigarh,921,935,977,1026,1080,1135,1197,1267,1340,1412,1480
30,Dadra & Nagar Haveli,228,223,233,246,260,274,290,310,330,348,364
31,Daman & Diu,164,178,190,201,212,223,234,244,255,265,277
32,Delhi,14150,14526,14952,15386,15831,16291,16760,17236,17725,18231,18758
33,Lakshadweep,61,66,68,70,71,73,74,75,75,76,76
34,Puducherry,980,973,1000,1037,1079,1123,1175,1239,1305,1369,1427
35,India,1039701,1055563,1072344,1089007,1105535,1121914,1138169,1154311,1170307,1186146,1201810

THE PROVIDED DATA FOR THE CAPSTONE PROJECT CONTAINS DATA OF THE YEAR 2012 ALSO SO TO FIND THE POPULATION OF DATA IN THE YEAR 2012 THE DATA WAS WEB SCRAPPED USING BEAUTIFUL SOUP FROM THE WEBSITE : "https://statistics.py.gov.in/state-wise-population-2012?page=3#:~:text=State%2Dwise%20Population%20%2D%202012%20;" TO ENSURE PROPER DATA COLLECTION.

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://statistics.py.gov.in/state-wise-population-2012?page=3#:~:text=State%2Dwise%20Population%20%2D%202012%20;'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table', class_='table table-bordered table-hover')
rows = table.find_all('tr')

data = []
for row in rows:
    columns = row.find_all('td')
    row_data = [column.text.strip() for column in columns]
    data.append(row_data)

# Create a DataFrame from the scraped data
df = pd.DataFrame(data, columns=['State Code', 'State', 'Total Population', 'Male Population', 'Female Population', 'Percentage', 'Sex_Ratio'])

# Print the DataFrame
print(df)

   State Code              State Total Population Male Population  \
0        None               None             None            None
1        None               None             None            None
2                          INDIA       1210193422       623724248
3          01    Jammu & Kashmir         12548926         6665561
4          02   Himachal Pradesh          6856509         3473892
5          03             Punjab         27704236        14634819
6          05        Uttarakhand         10116752         5154178
7          06            Haryana         25353081        13505130
8          08          Rajasthan         68621012        35620086
9          09       Uttarpradesh        199581477       104596415
10         10              Bihar        103804637        54185347
11         11             Sikkim           607688          321661
12         12  Arunachal Pradesh          1382611          720232
13         13           Nagaland          1980602         1025707
14         14            Manipur          2721756         1369764
15         15            Mizoram          1091014          552339
16         16            Tripura          3671032         1871867
17         17          Meghalaya          2964007         1492668
18         18              Assam         31169272        15954927
19         19        West Bengal         91347736        46927389
20         20          Jharkkand         32966238        16931688
21         21             Orissa         41947358        21201678
22         22        Chattisgarh         25540196        12827915
23         23     Madhya Pradesh         72597565        37612920
24         24            Gujarat         60383628        31482282
25         27        Maharashtra        112372972        58361397
26         28     Andhra Pradesh         84665533        42509881
27         29          Karnataka         61130704        31057742
28         30                Goa          1457723          740711
29         32             Kerala         33387677        16021290
30         33          Tamilnadu         72138958        36158871

   Female Population Percentage Sex_Ratio
0               None       None      None
1               None       None      None
2          586469174        100       940
3            5883365       1.04       883
4            3382617       0.57       974
5           13069417       2.29       893
6            4962574       1.38       963
7           11847951       2.09       877
8           33000926       5.67       926
9           94985062      16.49       908
10          49619290       7.00       916
11            286027       0.05       889
12            662379       0.11       920
13            954895       0.16       931
14           1351992       0.22       987
15            538675       0.09       975
16           1799165       0.30       961
17           1471339       0.24       986
18          15214345       2.58       954
19          44420347       2.72       947
20          16034550       2.72       947
21          20745680       3.47       978
22          12712281       2.11       991
23          34984645       6.00       930
24          28901346       4.99       918
25          54011575       9.29       925
26          42155652       8.58       992
27          30072962       5.05       968
28            717012       0.12       968
29          17366387       2.76      1084
30          35980087       5.96       995

In [ ]:
# Merge the two dataframes
merged_df = pd.concat([df1, df2], ignore_index=True)

print(merged_df)

REQ. NUMBER - 2

Literacy Rate in each state

In [15]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.census2011.co.in/literacy.php'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

table = soup.find('table')
rows = table.find_all('tr')

data = []

for row in rows[1:]: # Skip first row as it contains header
    columns = row.find_all('td')
    state = columns[1].text
    literacy_rate = columns[2].text
    Male= columns[3].text
    Female = columns[4].text
    Percentage_Change = columns[5].text
    
    data.append([state, literacy_rate, Male, Female, Percentage_Change])

# Create DataFrame
literacy_rate = pd.DataFrame(data, columns=['State', 'Literacy Rate', 'Male Literacy', 'Female Literacy', 'Percentage Change'])

# Display the DataFrame
print(literacy_rate)

                          State Literacy Rate Male Literacy Female Literacy  \
0                         India         74.04         82.14           65.46
1                        Kerala         94.00         96.11           92.07
2                   Lakshadweep         91.85         95.56           87.95
3                       Mizoram         91.33         93.35           89.27
4                           Goa         88.70         92.65           84.66
5                       Tripura         87.22         91.53           82.73
6                 Daman and Diu         87.10         91.54           79.55
7   Andaman and Nicobar Islands         86.63         90.27           82.43
8                         Delhi         86.21         90.94           80.76
9                    Chandigarh         86.05         89.99           81.19
10                   Puducherry         85.85         91.26           80.67
11             Himachal Pradesh         82.80         89.53           75.93
12                  Maharashtra         82.34         88.38           75.87
13                       Sikkim         81.42         86.55           75.61
14                   Tamil Nadu         80.09         86.77           73.44
15                     Nagaland         79.55         82.75           76.11
16                  Uttarakhand         78.82         87.40           70.01
17                      Gujarat         78.03         85.75           69.68
18                      Manipur         76.94         83.58           70.26
19                  West Bengal         76.26         81.69           70.54
20       Dadra and Nagar Haveli         76.24         85.17           64.32
21                       Punjab         75.84         80.44           70.73
22                      Haryana         75.55         84.06           65.94
23                    Karnataka         75.36         82.47           68.08
24                    Meghalaya         74.43         75.95           72.89
25                       Orissa         72.87         81.59           64.01
26                        Assam         72.19         77.85           66.27
27                 Chhattisgarh         70.28         80.27           60.24
28               Madhya Pradesh         69.32         78.73           59.24
29                Uttar Pradesh         67.68         77.28           57.18
30            Jammu and Kashmir         67.16         76.75           56.43
31               Andhra Pradesh         67.02         74.88           59.15
32                    Jharkhand         66.41         76.84           55.42
33                    Rajasthan         66.11         79.19           52.12
34            Arunachal Pradesh         65.38         72.55           57.70
35                        Bihar         61.80         71.20           51.50

   Percentage Change
0               8.66
1               3.14
2               5.19
3               2.53
4               6.69
5              14.03
6               8.92
7               5.33
8               4.54
9               4.11
10              4.61
11              6.32
12              5.46
13             12.61
14              6.64
15             12.96
16               7.2
17              8.89
18             10.33
19              7.62
20             18.61
21              6.19
22              7.64
23              8.72
24             11.87
25              9.79
26              8.94
27              5.62
28              5.58
29             11.41
30             11.64
31              6.55
32             12.85
33               5.7
34             11.04
35              14.8

REQ. NUMBER - 3

Area of each state

In [23]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table', class_='wikitable')
rows = table.find_all('tr')

data = []
for row in rows:
    columns = row.find_all('td')
    row_data = []
    for column in columns:
        row_data.append(column.text.strip())
    data.append(row_data)

df = pd.DataFrame(data)
print(df)

           0                                         1  \
0       None                                      None
1     1 (S1)                                 Rajasthan
2     2 (S2)                            Madhya Pradesh
3     3 (S3)                               Maharashtra
4     4 (S4)                             Uttar Pradesh
5     5 (S5)                                   Gujarat
6     6 (S6)                                 Karnataka
7     7 (S7)                            Andhra Pradesh
8     8 (S8)                                    Odisha
9     9 (S9)                              Chhattisgarh
10  10 (S10)                                Tamil Nadu
11  11 (S11)                                 Telangana
12  12 (S12)                                     Bihar
13  13 (S13)                               West Bengal
14  14 (S14)                         Arunachal Pradesh
15  15 (S15)                                 Jharkhand
16  16 (S16)                                     Assam
17  17 (UT1)                                    Ladakh
18  18 (S17)                          Himachal Pradesh
19  19 (S18)                               Uttarakhand
20  20 (S19)                                    Punjab
21   21(S20)                                   Haryana
22  22 (UT2)                         Jammu and Kashmir
23  23 (S21)                                    Kerala
24  24 (S22)                                 Meghalaya
25  25 (S23)                                   Manipur
26  26 (S24)                                   Mizoram
27  27 (S25)                                  Nagaland
28  28 (S26)                                   Tripura
29  29 (UT3)               Andaman and Nicobar Islands
30  30 (S27)                                    Sikkim
31  31 (S28)                                       Goa
32  32 (UT4)                                     Delhi
33  33 (UT5)  Dadra and Nagar Haveli and Daman and Diu
34  34 (UT6)                                Puducherry
35  35 (UT7)                                Chandigarh
36  36 (UT8)                               Lakshadweep
37                                               India

                          2              3             4     5
0                      None           None          None  None
1                   342,239        Western        10.414
2                   308,252        Central         9.376   [a]
3                   307,713        Western         9.359
4                   240,928       Northern         7.328
5                   196,024        Western         5.962
6                   191,791       Southern         5.833
7                   162,975       Southern         4.957   [b]
8                   155,707        Eastern         4.736
9                   135,192        Central         4.112   [c]
10                  130,058       Southern         3.956
11                  112,077       Southern         3.409
12                   94,163        Eastern         2.864
13                   88,752        Eastern         2.700
14                   83,743   Northeastern         2.548
15                   79,716        Eastern         2.424
16                   78,438   Northeastern         2.386
17          59,146(166,698)       Northern  1.800(5.079)   [d]
18                   55,673       Northern         1.693
19                   53,483       Northern         1.626
20                   50,362       Northern         1.531
21                   44,212       Northern         1.344
22           42,241(55,538)       Northern  1.285(1.689)   [e]
23                   38,863       Southern         1.182
24                   22,429   Northeastern         0.682
25                   22,327   Northeastern         0.680
26                   21,081   Northeastern         0.642
27                   16,579   Northeastern         0.505
28                   10,491   Northeastern         0.320
29                    8,249  Bay of Bengal         0.251
30                    7,096   Northeastern         0.217
31                    3,702        Western         0.112
32                    1,484       Northern         0.045
33                      603        Western         0.018   [5]
34                      479       Southern         0.015   [f]
35                      114       Northern         0.003
36                       32    Arabian Sea         0.001
37  3,287,263(3,166,414)[g]                  100(96.323)